server:
  port: 8848

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photograph_share?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  thymeleaf:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 20MB

#  spring.servlet.multipart.max-file-size=50MB
#  spring.servlet.multipart.max-request-size=50MB


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
